### ISSUE TITLE
请教一下如何对你的模型进行finetune呢？

### ISSUE THREAD

**Issue by xiewenqian** [mymusise/CPM-TF2Transformer#1]
请教一下如何对你的模型进行finetune呢？

**Comment by mymusise** [comment]
方法和huggingface上的其他模型是同样的方法，可以参考 https://huggingface.co/transformers/training.html

**Comment by NemoCoder** [comment]
可否将CPM-2-Pretrain转换为transformer版本呢

**Comment by mymusise** [comment]
> 可否将CPM-2-Pretrain转换为transformer版本呢

理论上可以的，有兴趣可以参考转换脚本
